### ISSUE TITLE
Do not run the hub daemon as root user

### ISSUE THREAD

**Issue by juliogonzalez** [uyuni-project/hub-xmlrpc-api#23]
https://linux-audit.com/how-and-why-linux-daemons-drop-privileges/

If you are not going to run with a port < 1024, and if you don't really access to any particular path or device you can't access as regular user, your daemon should not run as root user and even if you need such access, you should start as root and drop privileges.

You don't really need a new user, you could consider using the one that uyuni and susemanager provides (IIRC `susemanager`)

**Comment by juliogonzalez** [comment]
Needless to say, we need this fixed for SUSE Manager 4.1 GM, and for next Uyuni release if we really want users to start testing this on "production" environments.

**Comment by isbm** [comment]
Actually, you can run daemon as non root at port < 0x400 as easy as setting a capability. I do that every time, something like:

```
setcap 'cap_net_bind_service=+ep' /path/to/your/hub/stuff
```

However, you must ensure your bin is not looking into `LD_LIBRARY_PATH`.

**Comment by isbm** [comment]
@admd @juliogonzalez but also if you are running Go program as root, you  should worry. Because what you have in `vendor` doesn't mean you know it, audited it, cleaned it, maintaining it and sure it contains no `rm -rf /` on `OpenSocket()` for example :wink: And even if you do know what it is, that will vanish on your next `go mod tidy` or cache refresh.

If you know what I mean...

I guess, a serious work should be done for Go programs to package and each 3rd party stuff from source should be actually be a real src RPM in OBS, instead of taking whatever freshmeat on internets. I think @juliogonzalez already got a rough idea where it goes.

**Comment by moio** [comment]
I would suggest to take inspiration from the approach of Prometheus:

1. add global variables to the top of the specfile to define a user and a group
```
%global prometheus_user prometheus
%global prometheus_group %{prometheus_user}
```

2. add a %pre section similar to this to create user and group at package installation time
```
%pre
getent group %{prometheus_group} >/dev/null || %{_sbindir}/groupadd -r %{prometheus_group}
getent passwd %{prometheus_user} >/dev/null || %{_sbindir}/useradd -r -g %{prometheus_group} -d %{_localstatedir}/lib/prometheus -s /sbin/nologin %{prometheus_user}
``

3. make sure the service systemd file uses the same user
```
User=prometheus
```

References:
 * https://build.opensuse.org/package/view_file/server:monitoring/golang-github-prometheus-prometheus/prometheus.service?expand=1
 * https://build.opensuse.org/package/view_file/server:monitoring/golang-github-prometheus-prometheus/golang-github-prometheus-prometheus.spec?expand=1
